# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep
class TestTest01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    # self.driver.quit()
   pass
  
  def test_test01(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.find_element().send_keys()
    # sleep(1)
    # self.driver.set_window_size(550, 689)
    # sleep(1)
    # self.driver.find_element(By.ID, "kw").click()
    # sleep(1)
    # self.driver.find_element(By.ID, "kw").send_keys("lalal")
    # sleep(1)
    # self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    # sleep(1)
    # self.driver.find_element(By.LINK_TEXT, "LALAL.AI: 100% AI-Powered Vocal and Instrumental Track...").click()
  
