# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(3)
    self.vars = {}
  
  def teardown_method(self, method):
    # self.driver.quit()
     pass
  
  def test_test1(self):
    self.driver.get("http://192.168.50.23:8380/identify_orders/view?id=50")
    self.driver.set_window_size(1295, 704)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "scode").click()
    self.driver.find_element(By.ID, "scode").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    element = self.driver.find_element(By.LINK_TEXT, "商品管理")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "鉴定管理").click()
    element = self.driver.find_element(By.ID, "menu_identify_orders")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "menu_identify_orders").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mypage_button1:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(3) > a:nth-child(1)").click()
    element = self.driver.find_element(By.LINK_TEXT, "鉴定")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "鉴定").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".table_title > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".info > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".info > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "chooseSku").click()
    element = self.driver.find_element(By.XPATH, "(//a[@id=\'check_button\']/img)[2]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "(//a[@id=\'check_button\']/img)[2]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "保存").click()
    self.driver.find_element(By.ID, "agree").click()
    self.driver.find_element(By.ID, "identifyPrice").click()
    self.driver.find_element(By.ID, "identifyPrice").send_keys("1")
    self.driver.find_element(By.ID, "agree").click()
    self.driver.find_element(By.LINK_TEXT, "确定").click()
    self.driver.find_element(By.ID, "confirmButton").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myAlertDialog .btn").click()
    self.driver.find_element(By.ID, "identifyOver").click()
    self.driver.find_element(By.ID, "confirmButton").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myAlertDialog .btn").click()
    ses = ActionChains(self.driver)
    ses.click_and_hold()
    ses.context_click()
    ses.double_click()
    ses.drag_and_drop()